import type { Metadata } from "next";
import {  Imbue, Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-inter",
  subsets: ["latin"],
  display:"swap"
})
export const imbue = Imbue({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  variable: "--font-imbue",
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  antialiased bg-amber-50`}
      >
        {children}
      </body>
    </html>
  );
}
